[versions]
kotlin = "1.9.25"
spring-boot = "3.5.4"
dependency-management = "1.1.7"
mockk = "1.13.12"
testcontainers = "1.20.2"
java = "17"
flyway-mysql = "11.7.2"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway-mysql" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
spring-boot-starters = [
  "spring-boot-starter",
  "spring-boot-starter-actuator",
  "spring-boot-starter-web",
  "spring-boot-starter-validation",
  "spring-boot-starter-data-jpa",
  "spring-boot-starter-data-mongodb"
]